### ISSUE TITLE
Integrate Codecov ❓ 

### ISSUE THREAD

**Issue by islent** [julia-actions/example-workflows#3]
Thanks for the example workflows, but I couldn't find any instructions to integrate Codecov in github actions for julia. All I found were examples on Travis.
Is there any way of using Codecov workflows other than **uploading manually**？

**Comment by islent** [comment]
Something like this (https://github.com/codecov/example-julia):
```yml
after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
```
But I'm new to github actions and Codecov. An example might help many newbies like me :D

**Comment by SaschaMann** [comment]
You can use https://github.com/julia-actions/julia-uploadcodecov

```yaml
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

Check https://github.com/invenia/PkgTemplates.jl/blob/master/test/fixtures/AllPlugins/.github/workflows/ci.yml for a full example.

Alternatively the command you posted can be added as a step in the workflow, too:

```yaml
- name: Codecov
  run: julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
```
(untested, you might have to check the syntax in the workflow editor)

**Comment by islent** [comment]
Thanks a lot! This worked for me:
```yml
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
I'm closing this now :D
